services:
  # --- INFRASTRUTTURA ZABBIX ---
  zabbix-db:
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=root_pwd_sygest
      - MARIADB_USER=zabbix
      - MARIADB_PASSWORD=zabbix_pwd_sygest
      - MARIADB_DATABASE=zabbix
    volumes:
      - zabbix-db-data:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.0-latest
    environment:
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd_sygest
      - MYSQL_ROOT_PASSWORD=root_pwd_sygest
    ports:
      - "10051:10051"
    depends_on:
      - zabbix-db

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    environment:
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd_sygest
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Rome
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
      - zabbix-db

  # --- INFRASTRUTTURA SYGEST ---
  sygest-db:
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=root_pwd_sygest
      - MARIADB_DATABASE=progetto_sygest
    volumes:
      - sygest-db-data:/var/lib/mysql
      - ./progetto_sygest.sql:/docker-entrypoint-initdb.d/progetto_sygest.sql 
    ports:
      - "3306:3306"

  sygest-worker:
    build: .
    container_name: sygest-script-runner
    depends_on:
      - sygest-db
      - zabbix-server
    env_file:
      - .env
    volumes:
      # Sincronizza i file della cartella locale con quelli nel container
      - ./:/app 
    ports:
      - 5001:5000

volumes:
  zabbix-db-data:
  sygest-db-data:
